# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('timings', models.CharField(max_length=50)),
            ],
        ),
    ]
